// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sixgram.Stories.Database;

namespace Sixgram.Stories.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220318094808_Change_Name_Type_And_Add_Data_Seeding")]
    partial class Change_Name_Type_And_Add_Data_Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Sixgram.Stories.Database.Models.StoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("StoriesModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d51ff19d-df9c-43e7-b11f-36ea9fb7992a"),
                            DateCreated = new DateTime(2022, 3, 18, 12, 48, 7, 725, DateTimeKind.Local).AddTicks(3695),
                            Description = "Description",
                            FileId = new Guid("906eb56c-b191-4b0e-923d-c61741ff0b86"),
                            Name = "FirstStory",
                            UserId = new Guid("bd2f3673-0f3e-4260-b85f-ae6a0f9ff212")
                        },
                        new
                        {
                            Id = new Guid("e8c174c9-d93c-4092-9d3b-8881fd173bd7"),
                            DateCreated = new DateTime(2022, 3, 18, 12, 48, 7, 726, DateTimeKind.Local).AddTicks(5131),
                            Description = "Description",
                            FileId = new Guid("eb8528ea-a14d-443d-a963-e39f58d09f84"),
                            Name = "SecondStory",
                            UserId = new Guid("d9d10bc6-e1fe-42c9-9f14-08d1de011e41")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
